#pragma kernel CSMain

RWTexture2D<float4> Result;
StructuredBuffer<float> _ParameterBuffer;

[numthreads(8,8,1)]
void CSMain (uint3 id : SV_DispatchThreadID)
{
    // TODO: insert actual code here!

    //Result[id.xy] = float4(id.x & id.y, (id.x & 15)/15.0, (id.y & 15)/15.0, 0.0);
    float offset = _ParameterBuffer[0];
    float intensity = ((id.x + offset) % 256) / 256.0;
    Result[id.xy] = float4(intensity, intensity, intensity, 1);
}
